CREATE TABLE IF NOT EXISTS `ADM_USER` (
    `ID` int AUTO_INCREMENT  PRIMARY KEY,
    `USER_ID` varchar(50) NOT NULL,
    `USER_NAME` varchar(100) NOT NULL,
    `CREATE_TIME` TIMESTAMP NOT NULL,
    `CREATE_BY` varchar(50) NOT NULL,
    `UPDATE_TIME` TIMESTAMP DEFAULT NULL,
    `UPDATE_BY` varchar(50) DEFAULT NULL
  );

CREATE TABLE IF NOT EXISTS `SYS_API_LOG` (
  `ID` int AUTO_INCREMENT  PRIMARY KEY,
  `TXN_SEQ` varchar(50) NOT NULL,
  `USER_ID` varchar(50),
  `METHOD` varchar(100),
  `PARAMS` varchar(3000),
  `RESULT` varchar(3000),
  `ERROR_MSG` varchar(3000),
  `CREATE_TIME` TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `SYS_EXTERNAL_API_LOG` (
  `ID` int AUTO_INCREMENT  PRIMARY KEY,
  `TXN_SEQ` varchar(50) NOT NULL,
  `MSG_ID` varchar(50),
  `MSG_TYPE` varchar(1),
  `MSG_CONTENT` varchar(3000),
  `MSG_TIME` TIMESTAMP
);